<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>349de666-5ed4-4616-9944-a541e2c53f7c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABB.Catalogo.Entidades\ABB.Catalogo.Entidades.csproj" />
    <ProjectReference Include="..\ABB.Catalogo.LogicaNegocio\ABB.Catalogo.LogicaNegocio.csproj" />
  </ItemGroup>

</Project>
